fio = input("ФИО исследователя: ")
date = input("Сегодняшняя дата: ")
exp_name = input("Название эксперимента: ")
recap = input("Вывод: ")
with open("C:/Users/User/Desktop/journal.txt", "w", encoding="utf-8") as card:
    card.write(f"+--------------------------------------------------+\n")
    card.write(f"| Электронный лабораторный журнал                  \n")
    card.write(f"+--------------------------------------------------+\n")
    card.write(f"| ФИО исследователя : {fio}\n")
    card.write(f"| Дата исследования : {date}\n")
    card.write(f"| Эксперимент       : {exp_name}\n")
    card.write(f"+--------------------------------------------------+\n")
    card.write(f"| Вывод:                                           \n")
    card.write(f"| {recap}\n")
    card.write(f"+--------------------------------------------------+\n")
